-- MySQL Script generated by MySQL Workbench
-- Mon Sep  2 07:49:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital2b
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital2b
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital2b` ;
USE `hospital2b` ;

-- -----------------------------------------------------
-- Table `hospital2b`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital2b`.`paciente` (
  `idpaciente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NULL,
  `telefone` VARCHAR(9) NULL,
  PRIMARY KEY (`idpaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital2b`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital2b`.`medico` (
  `idmedico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `crm` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital2b`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital2b`.`consulta` (
  `idconsulta` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `local` VARCHAR(20) NOT NULL,
  `paciente_idpaciente` INT NOT NULL,
  `medico_idmedico` INT NOT NULL,
  PRIMARY KEY (`idconsulta`),
  INDEX `fk_consulta_paciente_idx` (`paciente_idpaciente` ASC) VISIBLE,
  INDEX `fk_consulta_medico1_idx` (`medico_idmedico` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_paciente`
    FOREIGN KEY (`paciente_idpaciente`)
    REFERENCES `hospital2b`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_medico1`
    FOREIGN KEY (`medico_idmedico`)
    REFERENCES `hospital2b`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital2b`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital2b`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





INSERT INTO usuario (email, senha) VALUES ("teste@teste.com", "123321");

INSERT INTO paciente (nome, cpf, telefone) VALUES ("PacienteA", "111.222.333-58", "987654321");
INSERT INTO paciente (nome, cpf, telefone) VALUES ("PacienteB", "222.555.333-26", "932124763");
INSERT INTO paciente (nome, cpf, telefone) VALUES ("PacienteC", "547.265.489-71", "953282733");

INSERT INTO medico (nome, crm, area) VALUES ("MedicoA", "66768", "Clínica Geral");
INSERT INTO medico (nome, crm, area) VALUES ("MedicoB", "4554", "Pediatria");
INSERT INTO medico (nome, crm, area) VALUES ("MedicoC", "87454", "Ortopedia");

INSERT INTO consulta (data, local, paciente_idpaciente, medico_idmedico) VALUES ("2024-12-31", "Sala X", 2, 1);
INSERT INTO consulta (data, local, paciente_idpaciente, medico_idmedico) VALUES ("2024-11-25", "Sala Y", 1, 3);
INSERT INTO consulta (data, local, paciente_idpaciente, medico_idmedico) VALUES ("2024-08-29", "Sala Y", 1, 2);
INSERT INTO consulta (data, local, paciente_idpaciente, medico_idmedico) VALUES ("2024-05-17", "Sala W", 3, 1);